version: "3.8"
services:
  database:
    container_name: database
    image: mongo:5.0.9
    ports:
      - "27017"
  zookeeper:
    container_name: zookeeper
    image: confluentinc/cp-zookeeper:7.2.0
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
    ports:
      - "2181"
  kafka:
    depends_on:
      - zookeeper
    container_name: kafka
    image: confluentinc/cp-kafka:7.2.0
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    ports:
      - "9092"
  users:
    container_name: users
    image: users:latest
    build:
      context: ./
      args:
        - module=users
  orders-read-side:
    container_name: orders-read-side
    image: orders-read-side:latest
    build:
      context: ./
      args:
        - module=orders-read-side
  orders-write-side:
    container_name: orders-write-side
    image: orders-write-side:latest
    build:
      context: ./
      args:
        - module=orders-write-side
  api-gateway:
    container_name: api-gateway
    image: api-gateway:latest
    build:
      context: ./
      args:
        - module=api-gateway
    ports:
      - "8080:8080"