name: Build

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: 11
          distribution: adopt

      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@v1

      - name: Change Gradle wrapper permissions
        run: chmod +x ./gradlew

      - name: Build images
        run: |
          docker build --build-arg module=orders-read-side -t orders-read-side ./
          docker build --build-arg module=orders-write-side -t orders-write-side ./
          docker build --build-arg module=users -t users ./

      - name: Build with Gradle
        run: ./gradlew build